travis:
  secure:
    BINSTAR_TOKEN: maqtxokuB9a/O2QGi/YBSSIUIgIKo3QgyathayhGJRYcCJDstB6uAJQTtBWcmwWtzhf9HRvqxgzEMUdP4rGhLtGU/HaauC2lTQkhFKBjruUGb12WgIWssNYwHBtlFEtkf6NbT+f60pX87sD57/LVSnPnd2q00yCv/3JyMSgpFhzXIieLyTc1r9K2Z/KJhNbIDTeErxmRGWK9gVgvwO9+qWP6ismmtejc8zcwNfv0yZOjzKcdaERhoqbcLv2xRkfNW+LsT/ribtwl8Hvm3f7XFcpf0S672CEsKyZqsy2QCGOTxieWdjpBjCQ/wAH8YiG7K9XX2+TuIxFJBkCUMMqCxl9cujloNkD4LP/l8lcNX9nhuDumeScik6gzR3KDxT/35AisajzSzrkgNtdzZNDmZVth9ADeY8JUkrGadAFdWSDCLTkYjZqVuf/aF6NeoZixEQHLMw8JC7g7pH0e/A7OEPNzRlpUxahoYEyTK0V4/TQ9qwAmQ21je6f1tDFK1ElyaI7vQPQwESFJivhnee6o1zCggtz6g3JfHcdLSfz+TPxDKgwvAbWW3jSuZv77QXu6AUmll6O/4JM942U/e+ENwBlYNYmm8WiwM92HGf+mJ1DjmVtdQcfo24Bl3X5lU4kaJHpBNFXRwyC6D8e4RbKD2W+VwW6Oggr2e6JOuqgjnLk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
